# Generated by Django 5.1.7 on 2025-04-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="firebase_uid",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
