# Generated by Django 5.1.7 on 2025-04-07 14:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_firebase_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models.cover_image_upload_path
            ),
        ),
    ]
