# Generated by Django 5.0.10 on 2025-04-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="media",
            field=models.ImageField(blank=True, null=True, upload_to="tweets_media/"),
        ),
    ]
