# Generated by Django 5.1.7 on 2025-03-21 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="media",
            field=models.FileField(blank=True, null=True, upload_to="tweets_media/"),
        ),
        migrations.AlterField(
            model_name="tweetmedia",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tweet_medias",
                to="tweets.tweet",
            ),
        ),
    ]
